### ISSUE TITLE
Implement flag that does not throw EmulationError on success == false

### ISSUE THREAD

**Issue by CatCoderr** [ton-org/sandbox#38]
**Is your feature request related to a problem? Please describe.**
When writing tests for my smart contracts, there is must-fail cases which should terminate VM with my own exit code.
Before it can be done by using `.toHaveTransaction` matcher with `success: false, exitCode: X` params. Now it throws exception making this matcher useless for failed transactions.

**Describe the solution you'd like**
Implement this flag on Blockchain object creation

**Describe alternatives you've considered**
Catch EmulationError in tests and compare exit codes, which adds some boilerplate.

**Additional context**
<img width="990" alt="image" src="https://github.com/ton-org/sandbox/assets/21067004/9bf7b63d-2edc-4cc0-92a8-3b895a6bf6b6">

**Comment by krigga** [comment]
`EmulationError` should only happen when the emulation itself fails for some reason, not when a tx just has a nonzero exit code (if that is the case, then it can be matched as you described). An example of when emulation fails is when an external message is rejected - the tx technically never happens in this case and therefore cannot be returned, but the vm exit code is provided for convenience purposes.

So, unless you can tell me the version of sandbox where this was not the case and you could match your failed emulation transactions using the matcher, I cannot do anything about this and this is considered intended behavior.

**Comment by CatCoderr** [comment]
The case when failed emulation produces transactions was on `@ton-community/sandbox": "^0.11.0` dependency. And with following smart contract code. For some reason after changing smart contract code with the same sandbox version as above - some test cases starts failing. Apparently the problem was in the contract itself. Thanks for explanation. 

```
() recv_external(slice in_msg) {
    set_gas_limit(50000);

    debug(["получили external сообщение"]);

    var signature = in_msg~load_bits(512);
    var cs = in_msg;
    ;; client data
    var msg_seqno = cs~load_uint(32);
    ;; stored data
    var (stored_seqno, public_key, dao_addr, nft_collection_addr) = load_deployer_data();

    debug(["прочитали данные: ", stored_seqno, " ", msg_seqno]);

    throw_unless(33, msg_seqno == stored_seqno);
    throw_unless(error::access_denied(), check_signature(slice_hash(in_msg), signature, public_key));

    accept_message();

    debug(["доступ разрешен, приняли сообщение"]);
}
```
